name: tmux
version: 2.3
summary: tmux is a terminal multiplexer (non-official)
description: |
  What is a terminal multiplexer?
  It lets you switch easily between several programs in one terminal,
  detach them (they keep running in the background) and reattach them to a different terminal.
  And do a lot more.
  snapcraft.yaml, https://github.com/shawn111/tmux.snap

grade: stable
confinement: classic

apps:
  tmux:
    command: bin/tmux

parts:
  tmux:
    plugin: autotools
    source: https://github.com/tmux/tmux.git
    source-type: git
    build-packages: [libevent-dev, libncurses5-dev, pkg-config]
    stage-packages: [libevent-2.0-5, libncurses5]
